# <center>Домашнее задание
# <center>Создаем Википедию
## Задание 1. Используя подход аналогичный torchvision, сделать свой класс датасета.   
(Задание 2. Необязательное д/з:   
1. Поэкспериментировать с разными архитектурами рекурренток: тип ячеек, слои, нормализация, методы оптимизации - см. файл hw14_task2)

In [1]:
from wiki2_utils import WikiText2Dataset  # импорт класса, созданного в соответствие с заданием 1

## <center>1.

## тестируем

In [2]:
dataset = WikiText2Dataset()

### a)

In [3]:
%%time
train_loader = dataset.get_train_loader()
val_loader = dataset.get_val_loader()
test_loader = dataset.get_test_loader()

Wall time: 3.13 s


In [4]:
list(train_loader)[0]

(tensor([[ 4,  5,  6,  ..., 17,  4,  7],
         [ 3, 11,  4,  ..., 11,  6, 23],
         [ 4, 23, 18,  ..., 10,  9,  5],
         ...,
         [41,  4,  4,  ...,  5,  4,  6],
         [ 4, 64,  7,  ...,  4, 15, 13],
         [35, 10, 20,  ..., 31, 10,  5]]),
 tensor([ 3, 11,  4,  ..., 46, 19,  4]))

In [5]:
list(train_loader)[0][0].shape

torch.Size([30, 128])

In [6]:
list(train_loader)[0][1].shape

torch.Size([3840])

In [7]:
list(val_loader)[0]

(tensor([[ 4,  5, 52,  ..., 15, 14,  7],
         [ 3,  4,  4,  ...,  9,  4, 11],
         [ 4, 12, 24,  ...,  8, 19,  4],
         ...,
         [ 4,  6,  8,  ..., 13,  4, 70],
         [47, 11, 20,  ...,  8, 27, 16],
         [ 9, 16, 15,  ...,  4,  4,  5]]),
 tensor([ 3,  4,  4,  ..., 29,  3, 15]))

In [8]:
list(test_loader)[0]

(tensor([[ 4,  6, 14,  ..., 15, 12, 29],
         [ 3,  6, 10,  ..., 15,  4, 16],
         [ 4, 11, 19,  ...,  7, 16,  8],
         ...,
         [ 5, 10, 10,  ...,  4, 11,  6],
         [11,  8,  9,  ..., 27,  5, 23],
         [ 6,  4,  8,  ...,  4,  4, 15]]),
 tensor([ 3,  6, 10,  ...,  3, 37,  5]))

### b)

In [12]:
print(dataset.symbol2idx)

defaultdict(<bound method Vocab._default_unk_index of <torchtext.vocab.Vocab object at 0x00000193E3398388>>, {'<unk>': 0, '<pad>': 1, '<sos>': 2, '<eos>': 3, ' ': 4, 'e': 5, 't': 6, 'a': 7, 'n': 8, 'o': 9, 'i': 10, 'r': 11, 's': 12, 'h': 13, 'd': 14, 'l': 15, 'u': 16, 'c': 17, 'm': 18, 'f': 19, 'g': 20, 'p': 21, 'w': 22, 'y': 23, 'b': 24, ',': 25, 'k': 26, '.': 27, 'v': 28, '<': 29, '>': 30, '@': 31, '1': 32, 'T': 33, '0': 34, '=': 35, 'A': 36, '"': 37, 'S': 38, 'C': 39, '2': 40, 'I': 41, 'M': 42, "'": 43, '9': 44, 'B': 45, '-': 46, 'H': 47, 'x': 48, 'P': 49, 'R': 50, 'D': 51, 'F': 52, ')': 53, '(': 54, 'W': 55, 'N': 56, 'L': 57, 'G': 58, '3': 59, '5': 60, '8': 61, 'J': 62, 'E': 63, 'O': 64, '4': 65, '6': 66, '7': 67, 'z': 68, 'j': 69, 'q': 70, 'U': 71, 'K': 72, 'V': 73, ';': 74, '–': 75, ':': 76, 'Y': 77, '/': 78, '—': 79, 'Z': 80, '%': 81, '$': 82, '[': 83, ']': 84, 'é': 85, 'Q': 86, 'X': 87, '&': 88, '!': 89, '’': 90, 'á': 91, 'í': 92, 'ā': 93, '£': 94, '°': 95, '?': 96, 'ó': 97, '+

In [13]:
print(dataset.idx2symbol)

['<unk>', '<pad>', '<sos>', '<eos>', ' ', 'e', 't', 'a', 'n', 'o', 'i', 'r', 's', 'h', 'd', 'l', 'u', 'c', 'm', 'f', 'g', 'p', 'w', 'y', 'b', ',', 'k', '.', 'v', '<', '>', '@', '1', 'T', '0', '=', 'A', '"', 'S', 'C', '2', 'I', 'M', "'", '9', 'B', '-', 'H', 'x', 'P', 'R', 'D', 'F', ')', '(', 'W', 'N', 'L', 'G', '3', '5', '8', 'J', 'E', 'O', '4', '6', '7', 'z', 'j', 'q', 'U', 'K', 'V', ';', '–', ':', 'Y', '/', '—', 'Z', '%', '$', '[', ']', 'é', 'Q', 'X', '&', '!', '’', 'á', 'í', 'ā', '£', '°', '?', 'ó', '+', '#', 'š', '−', 'è', 'ö', '×', 'ü', 'ä', 'ō', 'ʻ', 'ś', 'ć', '“', 'ç', 'ł', 'ø', '”', '₹', 'ã', 'µ', 'ì', 'ư', '\ufeff', 'Æ', '…', '→', 'ơ', 'Í', 'ñ', 'É', '☉', '‘', '*', '~', '⁄', 'Å', 'Ō', '²', 'ë', 'ệ', 'ī', 'ễ', 'à', 'ô', 'ă', 'ū', '^', 'ê', '♯', 'ú', 'ỳ', '‑', 'Î', 'μ', '≤', 'å', 'î', 'ل', 'ṃ', '～', 'Ā', '्', '†', '€', '±', 'ė', 'ž', '〈', '〉', '・', 'û', 'č', 'α', 'β', '½', 'Ø', 'đ', 'γ', 'ṭ', 'ị', '„', '♭', 'â', 'Đ', '̃', 'ا', 'ه', '჻', 'ṅ', 'ầ', 'ớ', '′', '⅓', '大', '空', '¡', '¥'

In [18]:
dataset.test_txt.examples[0].text[:20]

[' ',
 '<eos>',
 ' ',
 '=',
 ' ',
 'R',
 'o',
 'b',
 'e',
 'r',
 't',
 ' ',
 '<',
 'u',
 'n',
 'k',
 '>',
 ' ',
 '=',
 ' ']