In [1]:
import torch

In [2]:
torch.__version__

'1.5.0+cpu'

In [3]:
torch.zeros([3, 4])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [4]:
torch.ones([3, 4, 2])

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]])

In [5]:
torch.Tensor([[1,  2,  3,  4],
              [5,  6,  7,  8],
              [9, 10, 11, 12]])

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [6]:
x = torch.Tensor([[1,  2,  3,  4],
                  [5,  6,  7,  8],
                  [9, 10, 11, 12]])

In [7]:
x.size()

torch.Size([3, 4])

In [8]:
x.shape

torch.Size([3, 4])

In [9]:
x[0]

tensor([1., 2., 3., 4.])

In [10]:
x[1]

tensor([5., 6., 7., 8.])

In [11]:
x[0, 0]

tensor(1.)

In [12]:
x[:, 0]

tensor([1., 5., 9.])

In [13]:
x + 10

tensor([[11., 12., 13., 14.],
        [15., 16., 17., 18.],
        [19., 20., 21., 22.]])

In [14]:
x ** 2

tensor([[  1.,   4.,   9.,  16.],
        [ 25.,  36.,  49.,  64.],
        [ 81., 100., 121., 144.]])

In [15]:
y = torch.Tensor([[12, 11, 10, 9],
                  [8, 7, 6, 5],
                  [4, 3, 2, 1]])

In [16]:
x + y

tensor([[13., 13., 13., 13.],
        [13., 13., 13., 13.],
        [13., 13., 13., 13.]])

In [17]:
x * y

tensor([[12., 22., 30., 36.],
        [40., 42., 42., 40.],
        [36., 30., 22., 12.]])

In [18]:
x / y

tensor([[ 0.0833,  0.1818,  0.3000,  0.4444],
        [ 0.6250,  0.8571,  1.1667,  1.6000],
        [ 2.2500,  3.3333,  5.5000, 12.0000]])

In [19]:
x % y

tensor([[1., 2., 3., 4.],
        [5., 6., 1., 3.],
        [1., 1., 1., 0.]])

In [20]:
torch.exp(x)

tensor([[2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01],
        [1.4841e+02, 4.0343e+02, 1.0966e+03, 2.9810e+03],
        [8.1031e+03, 2.2026e+04, 5.9874e+04, 1.6275e+05]])

In [21]:
torch.log(x)

tensor([[0.0000, 0.6931, 1.0986, 1.3863],
        [1.6094, 1.7918, 1.9459, 2.0794],
        [2.1972, 2.3026, 2.3979, 2.4849]])

In [22]:
torch.sin(x)

tensor([[ 0.8415,  0.9093,  0.1411, -0.7568],
        [-0.9589, -0.2794,  0.6570,  0.9894],
        [ 0.4121, -0.5440, -1.0000, -0.5366]])

In [23]:
x > 3

tensor([[False, False, False,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [24]:
mask = x > 3

In [25]:
x[mask]

tensor([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [26]:
x[x > 3]

tensor([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [27]:
y = x
y[0, 0] = 999
print(x)
print(y)

tensor([[999.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.],
        [  9.,  10.,  11.,  12.]])
tensor([[999.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.],
        [  9.,  10.,  11.,  12.]])


In [28]:
x = torch.Tensor([[1,  2,  3,  4],
                  [5,  6,  7,  8],
                  [9, 10, 11, 12]])

In [29]:
y = x.clone()
y[0, 0] = 999
print(x)
print(y)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[999.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.],
        [  9.,  10.,  11.,  12.]])


In [30]:
x.dtype

torch.float32

In [31]:
x = x.double()
print(x)
x = x.int()
print(x)
x = x.float()
print(x)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]], dtype=torch.float64)
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]], dtype=torch.int32)
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [32]:
import numpy as np
x = np.array([[1, 2, 3, 4],
              [4, 3, 2, 1]])
x

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [33]:
x = torch.from_numpy(x)
x

tensor([[1, 2, 3, 4],
        [4, 3, 2, 1]], dtype=torch.int32)

In [34]:
x = x.numpy()
x

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [35]:
v = torch.rand(100)

In [36]:
v.reshape((-1,20))

tensor([[0.8648, 0.8847, 0.7592, 0.7293, 0.8291, 0.1206, 0.5556, 0.6603, 0.4726,
         0.9892, 0.6773, 0.2876, 0.9430, 0.9713, 0.4030, 0.0442, 0.8430, 0.5265,
         0.1095, 0.0189],
        [0.9331, 0.7811, 0.9437, 0.5514, 0.7609, 0.1660, 0.3132, 0.6706, 0.8109,
         0.5117, 0.0062, 0.9235, 0.6330, 0.5434, 0.9839, 0.4632, 0.0091, 0.6128,
         0.7870, 0.0877],
        [0.3469, 0.9608, 0.9773, 0.8913, 0.5147, 0.4080, 0.9500, 0.9712, 0.3539,
         0.7417, 0.1650, 0.5301, 0.7120, 0.9776, 0.3414, 0.2437, 0.4040, 0.0898,
         0.2729, 0.0545],
        [0.2076, 0.2021, 0.7697, 0.5139, 0.9263, 0.4909, 0.0693, 0.2409, 0.9555,
         0.1327, 0.4894, 0.5726, 0.4097, 0.7690, 0.5394, 0.3751, 0.5067, 0.8695,
         0.0482, 0.2436],
        [0.5581, 0.8505, 0.4424, 0.3634, 0.1239, 0.7700, 0.5076, 0.4744, 0.8975,
         0.2563, 0.7159, 0.1138, 0.7092, 0.9434, 0.1250, 0.8760, 0.3069, 0.7669,
         0.8349, 0.1152]])

In [37]:
v.view((-1, 20))

tensor([[0.8648, 0.8847, 0.7592, 0.7293, 0.8291, 0.1206, 0.5556, 0.6603, 0.4726,
         0.9892, 0.6773, 0.2876, 0.9430, 0.9713, 0.4030, 0.0442, 0.8430, 0.5265,
         0.1095, 0.0189],
        [0.9331, 0.7811, 0.9437, 0.5514, 0.7609, 0.1660, 0.3132, 0.6706, 0.8109,
         0.5117, 0.0062, 0.9235, 0.6330, 0.5434, 0.9839, 0.4632, 0.0091, 0.6128,
         0.7870, 0.0877],
        [0.3469, 0.9608, 0.9773, 0.8913, 0.5147, 0.4080, 0.9500, 0.9712, 0.3539,
         0.7417, 0.1650, 0.5301, 0.7120, 0.9776, 0.3414, 0.2437, 0.4040, 0.0898,
         0.2729, 0.0545],
        [0.2076, 0.2021, 0.7697, 0.5139, 0.9263, 0.4909, 0.0693, 0.2409, 0.9555,
         0.1327, 0.4894, 0.5726, 0.4097, 0.7690, 0.5394, 0.3751, 0.5067, 0.8695,
         0.0482, 0.2436],
        [0.5581, 0.8505, 0.4424, 0.3634, 0.1239, 0.7700, 0.5076, 0.4744, 0.8975,
         0.2563, 0.7159, 0.1138, 0.7092, 0.9434, 0.1250, 0.8760, 0.3069, 0.7669,
         0.8349, 0.1152]])

In [38]:
x = torch.rand([2000, 3000])
# x

In [39]:
torch.cuda.is_available()

False

In [40]:
torch.device('cuda:0')

device(type='cuda', index=0)

In [41]:
torch.device('cpu')

device(type='cpu')

In [42]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
device

device(type='cpu')

In [43]:
x_cuda = x.to(device)
# x_cuda

In [44]:
x[0]

tensor([0.8165, 0.7703, 0.8682,  ..., 0.9795, 0.2212, 0.3671])

In [45]:
x_cuda[0]

tensor([0.8165, 0.7703, 0.8682,  ..., 0.9795, 0.2212, 0.3671])

In [50]:
%time y = (x - x + x * 10.0) ** 2

Wall time: 38.9 ms


In [51]:
%time y_cuda = (x_cuda - x_cuda + x_cuda * 10.0) ** 2

Wall time: 41.9 ms
